
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
  mail:
    host: smtp.gmail.com
    port: 587
    username: premkumar05604@gmail.com
    password: dfjg dyck pzfe xxqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cds:
  data-source.auto-config.enabled: false
  security:
    mock:
      users:
        - name: prem@inflexiontechfze.com
          password: Premkumar@97
          roles:
            - Admin
          additional:
            firstName: Premkumar
            lastName: S
            email: prem@inflexiontechfze.com
        - name: dhanush@inflexiontechfze.com
          password: Dhanush@123
          roles:
            - ProjectManager
          additional:
            firstName: Dhanush
            lastName: M
            email: dhanush@inflexiontechfze.com
        - name: sanjay@inflexiontechfze.com
          password: Sanjay@143
          roles:
            - Employee
          additional:
            firstName: Sanjay
            lastName: Kumar
            email: sanjay@inflexiontechfze.com
        - name: pugazh@inflexiontechfze.com
          password: Pugazh@321
          roles:
            - HRManager
          additional:
            firstName: Pugazh
            lastName: K
            email: pugazh@inflexiontechfze.com
